#!/bin/bash
if [ -e /dev/cedar_dev ]; then
	export VDPAU_DRIVER=sunxi
	export VDPAU_OSD=1
fi
SUDO=
if [ -x /usr/bin/omxplayer ]; then
	PLAYER=omx
	OMXPLAYER_DBUS_ADDR="/tmp/omxplayerdbus.${USER}"
	OMXPLAYER_DBUS_PID="/tmp/omxplayerdbus.${USER}.pid"
	export DBUS_SESSION_BUS_ADDRESS=`cat $OMXPLAYER_DBUS_ADDR`
	export DBUS_SESSION_BUS_PID=`cat $OMXPLAYER_DBUS_PID`
else
	PLAYER=mpv
	SUDO=sudo
fi
case $1 in
	eject)
		screen -S player -p 0 -X stuff "q" > /dev/null 2> /dev/null
		killall omxplayer > /dev/null 2> /dev/null
		$SUDO /usr/bin/killall mpv > /dev/null 2> /dev/null
		sleep 2
		;;
	play)
		src="$2"
		sub="`echo "$src" | sed -n 's|^\(/.*\)\.[^.]*$|\1.srt|p'`"
		$0 eject
		if [ "$PLAYER" = omx ]; then
			if [ -f "$sub" ]; then
				screen -md -S player omxplayer --lines 5 \
				--align center --subtitles "$sub" -b "$src"
			else
				screen -md -S player omxplayer -b "$src"
			fi
		else
			screen -md -S player $SUDO /usr/bin/xinit /usr/bin/mpv --input-unix-socket=/tmp/mpv.sock "$src"
		fi
		;;
	pause)
		if [ "$PLAYER" = omx ]; then
			screen -S player -p 0 -X stuff "p"
		else
			echo cycle pause | $SUDO /usr/bin/socat - /tmp/mpv.sock
		fi
		;;
	ff)
		if [ "$PLAYER" = omx ]; then
			screen -S player -p 0 -X stuff $'\e'[C
		else
			echo seek +30 | $SUDO /usr/bin/socat - /tmp/mpv.sock
		fi
		;;
	ffff)
		if [ "$PLAYER" = omx ]; then
			screen -S player -p 0 -X stuff $'\e'[A
		else
			echo seek +300 | $SUDO /usr/bin/socat - /tmp/mpv.sock
		fi
		;;
	rr)
		if [ "$PLAYER" = omx ]; then
			screen -S player -p 0 -X stuff $'\e'[D
		else
			echo seek -30 | $SUDO /usr/bin/socat - /tmp/mpv.sock
		fi
		;;
	rrrr)
		if [ "$PLAYER" = omx ]; then
			screen -S player -p 0 -X stuff $'\e'[B
		else
			echo seek -300 | $SUDO /usr/bin/socat - /tmp/mpv.sock
		fi
		;;
	volup)
		if [ "$PLAYER" = omx ]; then
			screen -S player -p 0 -X stuff "+"
		else
			echo add volume 5 | $SUDO /usr/bin/socat - /tmp/mpv.sock
		fi
		;;
	voldown)
		if [ "$PLAYER" = omx ]; then
			screen -S player -p 0 -X stuff "-"
		else
			echo add volume -5 | $SUDO /usr/bin/socat - /tmp/mpv.sock
		fi
		;;
	subminus)
		if [ "$PLAYER" \!= omx ]; then
			echo sub_delay -1 | $SUDO /usr/bin/socat - /tmp/mpv.sock
		fi
		;;
	subplus)
		if [ "$PLAYER" \!= omx ]; then
			echo sub_delay +1 | $SUDO /usr/bin/socat - /tmp/mpv.sock
		fi
		;;
	info)
		if [ "$PLAYER" = omx ]; then
			if [ "`ps ax | grep omxplayer | grep -v grep`" ]; then
	                        total="`   dbus-send --print-reply=literal --session --reply-timeout=500 --dest=org.mpris.MediaPlayer2.omxplayer /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Duration | sed -n 's|.*\ \([0-9]*\)[0-9][0-9][0-9][0-9][0-9][0-9]|\1|p'`"
				[ -n "$total" ] || total=0
				current="` dbus-send --print-reply=literal --session --reply-timeout=500 --dest=org.mpris.MediaPlayer2.omxplayer /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Position | sed -n 's|.*\ \([0-9]*\)[0-9][0-9][0-9][0-9][0-9][0-9]|\1|p'`"
				[ -n "$current" ] || current=0
				filename="`dbus-send --print-reply=literal --session --reply-timeout=1500 --dest=org.mpris.MediaPlayer2.omxplayer /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.GetSource`"
				filename="`basename "$filename"`"
			else
				status="stopped"
			fi
                else
			if [ \! -e /tmp/mpv.sock ]; then
				status="stopped"
			else
                                 filename="`echo '{ "command": ["get_property", "filename"] }'       | $SUDO /usr/bin/socat - /tmp/mpv.sock | sed 's|.*data":\(.*\),"error.*|\1|'`"
			         current="`echo '{ "command": ["get_property", "playback-time"] }'   | $SUDO /usr/bin/socat - /tmp/mpv.sock | sed 's|.*data":\(.*\),"error.*|\1|'`"
			         total="`echo '{ "command": ["get_property", "length"] }'            | $SUDO /usr/bin/socat - /tmp/mpv.sock | sed 's|.*data":\(.*\),"error.*|\1|'`"
			fi
		fi
		if [ "$status" = "stopped" ]; then
			echo "{ \"status\": \"stopped\" }"
		else
			echo "{ \"status\": \"playing\", \"filename\": \"${filename}\", \"current\": $current, \"total\": $total }"
		fi
		;;
	*)
		exit 1
esac
